### ISSUE TITLE
Some typo on http://jooby.org/doc/morphia/

### ISSUE THREAD

**Issue by j2rome** [jooby-project/site-generator#2]
- On the sentence : Extends the mongodb module with object-document mapping via Morphia.
  Linkto morphia is wrong : http://jooby.org/doc/morphia/%5BMorphia%5D%28https://github.com/mongodb/morphia%29
- Syntax error : 
  
  <pre>
  {
      use(new Monphia()
              .doWith((morphia, config) -> {
                  // work with morphia
                  morphia.map(Object.class);
              });   <---- delete semi colon
      );
  }
  </pre>
- auto-incremental ID
  
  <pre>
  {
  use(new Monphia().idGen(IdGen.GLOBAL); // or IdGen.LOCAL
  }
  </pre>
  
  API has changed  :
  
  <pre>
  {
  use(new Monphia().with(IdGen.GLOBAL); // or IdGen.LOCAL
  }
  </pre>
- Why Monphia instead of Morphia ? It is a typo or to avoid name clash with org.mongodb.morphia.Morphia ?

Do you prefer a merge request ? 
Thanks for your work.

**Comment by jknack** [comment]
No need for a pull request, thanks.

Yes, want to avoid name clash.. Do you have a better name to suggest?

There a few modules where we add `by` to the end, like: `Morphiaby` but not sure if that is better or not.

**Comment by j2rome** [comment]
- Why not suffix modules with Module e.g. MorphiaModule  ?
  For example in spring-data all clients exposed are clientName with the suffix "Template" : *_ElasticsearchTemplate.
  *_ MongoTemplate.
  It seems to be reasonable to use the Module concept of Jooby to make the same naming convention.
- Or a suffix with bootstrap, e.g. MorphiaBootstrap, it exposes the goal of the module but the module do more than just bootstrap...
- Or a suffix containing the description tool, e.g.MorphiaDocumentMapper, but not sure to be clear.

**Comment by jknack** [comment]
don't like long names, think will leave it as it is

**Comment by jknack** [comment]
fixed.
